### PR TITLE
P3 versions of the components

### PR DESCRIPTION
**Pull request by YuriyVaadin**
Connected to https://github.com/vaadin/components-team-tasks/issues/335

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/base-starter-react/4)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 36 at r1](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9K_d4L3JtX0Td-jzaI:-L9K_d4L3JtX0Td-jzaJ:b-pga0u1) ([raw file](https://github.com/vaadin/base-starter-react/blob/477f2869eb4c6978a2729d6f0d7ae90dbf218acb/README.md#L36)):*
> ```Markdown
> ```
> 
> Open `src/App.js` and in the `class`.
> ```

the text "and in the class" should be moved to the line below ("Define a constructor with a simple property:")

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by platosha** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/App.js, line 3 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9L63Av8p2BgsabpbRm:-L9L63Av8p2BgsabpbRn:b-rx8hf1) ([raw file](https://github.com/vaadin/base-starter-react/blob/cfb26c876e01d756ae5caf72d5b0b7cdca446b9e/src/App.js#L3)):*
> ```JavaScript
> import React, { Component } from 'react';
> 
> import '@webcomponents/webcomponentsjs/webcomponents-loader.js';
> ```

BTW I don’t have a strong reference, but feels like the polyfill should rather be added to `index.js`. Just to indicate that it’s a global thing, not just the App dependency.

---

*[src/App.js, line 23 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9L5Idq-XLbfrsaHSVL:-L9L5Idq-XLbfrsaHSVM:b3s65gm) ([raw file](https://github.com/vaadin/base-starter-react/blob/cfb26c876e01d756ae5caf72d5b0b7cdca446b9e/src/App.js#L23)):*
> ```JavaScript
>     return (
>       <div className="App">
>         <vaadin-text-field ref="text" placeholder="Type Something"></vaadin-text-field>
> ```

BTW now that we’re looking here,

String refs is a legacy API in React: https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

Maybe update to ref objects?  https://reactjs.org/docs/refs-and-the-dom.html#creating-refs

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by YuriyVaadin** [comment]
Review status: 5 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/App.js, line 3 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9L63Av8p2BgsabpbRm:-L9Os0a1D3hvBeoy7Ebk:b-896fix) ([raw file](https://github.com/vaadin/base-starter-react/blob/cfb26c876e01d756ae5caf72d5b0b7cdca446b9e/src/App.js#L3)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW I don’t have a strong reference, but feels like the polyfill should rather be added to `index.js`. Just to indicate that it’s a global thing, not just the App dependency.
</blockquote></details>

Done.

---

*[src/App.js, line 23 at r2](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9L5Idq-XLbfrsaHSVL:-L9Os0LuEAZ6jE3Gpl_g:b-896fix) ([raw file](https://github.com/vaadin/base-starter-react/blob/cfb26c876e01d756ae5caf72d5b0b7cdca446b9e/src/App.js#L23)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW now that we’re looking here,

String refs is a legacy API in React: https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs

Maybe update to ref objects?  https://reactjs.org/docs/refs-and-the-dom.html#creating-refs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-:-L9Owktr1eJOblKXtSkG:bnfp4nl)*

**Comment by platosha** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[README.md, line 41 at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9OwrG3BAfWincvlxze:-L9OwrG3BAfWincvlxzf:b-dww6fw) ([raw file](https://github.com/vaadin/base-starter-react/blob/29238c8f9a38d45ee1e691178146693314ed6e54/README.md#L41)):*
> ```Markdown
> 
> ``` typescript
> import '@webcomponents/webcomponentsjs/webcomponents-loader.js';
> ```

Oh please update this in the README too. This line should go to `src/index.js`, now that it’s changed in the code.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by YuriyVaadin** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 41 at r3](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4#-L9OwrG3BAfWincvlxze:-L9P1H-bDiI_span1-Z0:b-896fix) ([raw file](https://github.com/vaadin/base-starter-react/blob/29238c8f9a38d45ee1e691178146693314ed6e54/README.md#L41)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Oh please update this in the README too. This line should go to `src/index.js`, now that it’s changed in the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/base-starter-react/4)*

**Pull request merged**
